sudo: false

language: go

go:
  - "1.12"

git:
  depth: 1

addons:
  apt:
    update: true
    packages:
    - hugo

script:
  - git submodule init
  - git submodule update
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
