sudo: false

language: go

git:
  depth: 1

install: 
  - git clone https://github.com/udhos/update-golang --depth=1
  - cd update-golang
  - sudo ./update-golang.sh
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git --depth=1
  - cd hugo
  - go install
  - cd

script:
  - git submodule init
  - git submodule update
  - hugo

  # Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master