sudo: false

language: go

git:
  depth: 1

before_install: 
  # Install Go 1.12
  # I hate it.
  - sudo rm -rf /usr/local/go
  - curl https://dl.google.com/go/go1.12.14.linux-amd64.tar.gz -o GO_BIN.tar.gz
  - sudo tar -C /usr/local -xzf GO_BIN.tar.gz

install:
  # Install Hugo
  - go get github.com/gohugoio/hugo

script:
  - git submodule init
  - git submodule update
  - hugo

  # Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master