baseurl = "https://ycao.cc/"
title = "Yi's Home"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
googleAnalytics = "UA-150735695-1"

[taxonomies]
  series = "series"

[params]
    author = "Yi Cao"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Yi's xkcd-like comics. Click the book icon to see them.
    """
    publicationYear = "2020"
    listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/__yicao__"
    weight = 20

[[menu.main]]
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/xiaoyu2006"
    weight = 30

[[menu.main]]
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:caoyi06@qq.com"
    weight = 40